### ISSUE TITLE
should i add a routes.rb to the assets_path?

### ISSUE THREAD

**Issue by huobazi** [railsware/js-routes#146]
I want to use mina for deploy my rails app,
and a see  mina use `diff` to check if the files was changed

https://github.com/mina-deploy/mina/blob/3743585210c6687a8c9c18ca6bfc8a28204d674a/lib/mina/rails.rb#L197

so i think if i should add the ```routes.rb```to assets path

http://nadarei.co/mina/docs/lib/mina/rails.html#asset-paths
https://github.com/mina-deploy/mina/blob/master/lib/mina/rails.rb#L53

should do a assets.paths?
```
Rails.application.config.assets.paths << Rails.root.join("config", "routes.rb")
```
or only setting it in mina 
```
set_default :asset_paths, ['vendor/assets/', 'app/assets/','config/routes.rb']
```

any response will be greatly appreciated.

**Comment by andrewhavens** [comment]
@huobazi Your `config/routes.rb` has nothing to do with assets. You should *not* add `config/routes.rb` as an asset path.

**Comment by huobazi** [comment]
@aaronjensen  if i add a new route or change a route path the  xxx_uath() in routes.js will be changed
but the gem `mina` dose not know the routes.js was changed, bucause it use ``` diff ``` to check if the files was changed

**Comment by le0pard** [comment]
I don't know how it handle mina, but capistrano handle changed assets by running every time rake task `assets:precompile`, which handle what files changed and what didn't (by folder `cache`).

**Comment by huobazi** [comment]
@le0pard  
mina handle changed assets by  ` diff  ` the asset_paths 
if the asset_paths NOT CHANGE mina skip the ` ake task assets:precompile `
https://github.com/mina-deploy/mina/blob/3743585210c6687a8c9c18ca6bfc8a28204d674a/lib/mina/rails.rb#L197

**Comment by le0pard** [comment]
I think, it is problem of mina, because in this case, if you have erb code in js - it also will not run this task. Example:

```js
var SomeVar = <%= TIMEZONES_CONSTANTS.to_json %>
```

If you will change constant TIMEZONES_CONSTANTS in Ruby - this code will not change, but should be recompiled. js-routes have hook https://github.com/railsware/js-routes/blob/master/lib/js_routes/engine.rb#L17 which check `config/routes.rb` for changes to recompile by `asset:precompile` task.

So answer very simple: `config/routes.rb` has nothing to do with assets. You should not add `config/routes.rb` as an asset path. You should fix this problem by mina. (as wrote @andrewhavens)

**Comment by andrewhavens** [comment]
@huobazi @le0pard Ironically, I just ran into this issue in a different context. We are working on some Cucumber tests and Capybara sets a different port for the app to run on every test run. Since the `routes.js.erb` is an `.erb` file, the file is cached in the asset pipeline, even though we are dynamically setting a different port on every test run. The solution for us so far has been to run the `tmp:cache:clear` rake task on every test run. But I'm not sure if this is a suitable solution for production deployments.

**Comment by d4be4st** [comment]
this is a mina problem. It uses a diff to see if any assets files have been changed before attempting to precompile them.

There are two solutions:
1) Add a new empty line to your js files
2) use `invoke :'rails:assets_precompile:force'` insteead of `invoke :'rails:assets_precompile'` in your deploy.rb script

**Comment by bogdan** [comment]
Maybe you can run force vs not force based on if there are changes in routes.rb. If it is possible in mina, it should help you.
