### ISSUE TITLE
Can't use id as a querystring parameter

### ISSUE THREAD

**Issue by phstc** [railsware/js-routes#228]
Hi

I have a route like this:

```ruby
resources :classes
```

and depending on the flow I may call the index action `GET classes_path` passing an `id` as a parameter:

```javascript
Routes.classes_path(id: '123abc')
```

That used to work fine with 0.9.9, generating `/classes?id=123abc`, whereas with the latest version 1.4.1, it generates `/classes.123abc`. Is it a bug or expected behavior with the new version?

**Comment by bogdan** [comment]
Yes, this is expected now due to the following issue. In Rails:

``` ruby
classes_path(Model.new(id:1)) # => "/classes.1"
```

In JS we don't know the difference between an object and serialized model because there is no difference between object and hash. That is why we treat `{id: '123abc'}` as serialized object and give you the rails behavior. You need to pass special options key into a hash to make let js-routes know the last argument is options but not serialized model:

``` js
Routes.classes_path(id: '123abc', _options: true)
```

**Comment by hewrin** [comment]
I seem to get an `id is undefined error` when I try this, do we need to configure anything?

**Comment by bogdan** [comment]
Can you bring me the JS code you wrote, routes and line of JS code that raises an error inside js-routes? And also the version of js-routes gem.

**Comment by hewrin** [comment]
I'm sorry it was just a typo. Sorry for taking your time.
