### ISSUE TITLE
How to make it works with webpacker?

### ISSUE THREAD

**Issue by dbelyaeff** [railsware/js-routes#237]
Rails 5.2 introduce Webpacker gem which can help you to avoid using Sprockets.

Is there any way to make JS-Routes usable with Webpacker?

**Comment by le0pard** [comment]
Generate separate file from js-routes and use it in webpack. For any routes change you need regenerate this file.

**Comment by codemotion** [comment]
Is there any way to automate this?

**Comment by le0pard** [comment]
@codemotion rake task?

**Comment by le0pard** [comment]
I think `require('./routes.js')` can work with ES6 module system - no need to apply it on `window`.

**Comment by bogdan** [comment]
I think we should add a doc on that to readme.

**Comment by gtarsia** [comment]
I created my own webpack loader for the routes, so it would rebuild when you changes `routes.rb`. It worked but it would take 6 seconds to fully build, because it had to reload the whole rails app.
 
I would recommend writing your own generator instead of a rake task because of the meaning of what this is doing.  
```ruby
# lib/generators/routes_generator.rb
class RoutesGenerator < Rails::Generators::Base
  def create_initializer_file
    create_file "app/javascript/routes.js", JsRoutes.generate
  end
end
```
And use your own path/options. This way you don't need to remember options to pass to `rake js:routes`.

**Comment by hadees** [comment]
@gtarsia but you still have to use `Sprockets` correct?  There seems like you shouldn't need it though.

**Comment by ProGM** [comment]
Another option to use js-routes with webpacker is this:

## Add `rails-erb-loader`

    yarn add rails-erb-loader

## Setup the erb loader
Create a file in `config/webpack/loaders/erb.js`:
```javascript
module.exports = {
  test: /\.js\.erb$/,
  enforce: 'pre',
  exclude: /node_modules/,
  use: [{
    loader: 'rails-erb-loader',
    options: {
      runner: (/^win/.test(process.platform) ? 'ruby ' : '') + 'bin/rails runner'
    }
  }]
}
```

Then load it in `environment.js`:
```javascript
...
const erb =  require('./loaders/erb')
...
environment.loaders.append('erb', erb)
```

## Create a js-routes file:
Go into `app/javascripts` and create a `js-routes.js.erb` file, then paste:

```erb
<%= JsRoutes.generate() %>
```

Then you can simply import it as an es6 module, like this:

app/javascripts/packs/application.js

```
import Routes from '../js-routes.js.erb';

console.log(Routes.your_custom_path)
```

Hoping you can find it useful ;)

**Comment by paulodeon** [comment]
@ProGM your solution works, a couple of points to note:

You can install the erb loader using `bundle exec rails webpacker:install:erb`
You'll need to uncomment the `require "sprockets/railtie"` line in your `application.rb`
You can avoid the `.js.erb` in the `import` if you add `- .js.erb` to `extensions` in `webpacker.yml`

**Comment by ElMassimo** [comment]
If you are looking for a solution that plays nicely with Webpacker, you might want to check out [`js_from_routes`](https://github.com/ElMassimo/js_from_routes).

Although it doesn't come with a default implementation for [url interpolation](https://github.com/ElMassimo/js_from_routes/blob/master/spec/support/sample_app/app/javascript/helpers/UrlHelper.js#L22-L31), it's [very flexible](https://gist.github.com/ElMassimo/cab56e64e20ff797f3054b661a883646) and you can generate code that uses your own API helpers.

**Comment by marvinthepa** [comment]
@paulodeon 

>     * You'll need to uncomment the `require "sprockets/railtie"` line in your `application.rb`

Sounds like this might not be necessary anymore with #257 fixed (released in v1.4.10).

**Comment by stoplion** [comment]
I'm also using Webpacker

in `application.js` addeda a..
`require('js-routes');`

getting a..
`Module not found: Error: Can't resolve 'js-routes' in `

**Comment by marvinthepa** [comment]
@stoplion there is not file that is generated that is called "js-routes.js". The default path is still `app/assets/javascripts/routes.js`, see https://github.com/railsware/js-routes/blob/b52648aefc38a5c00e66a410765ed608a9de2e46/lib/js_routes.rb#L15.

You can change that:

```diff
+++ b/config/initializers/js_routes.rb
@@ -0,0 +1,3 @@
+JsRoutes.setup do |config|
+  config.file = "app/javascript/js-routes.js"
+end
```

but even then, you need `require('../js-routes')` instead of `require('js-routes')`. Or you can use`import Routes from '../js-routes'` in the files that use the `Routes` object.

**Comment by bogdan** [comment]
I made a few patches to make it more compatible with webpacker:

* Default generation file is now at `app/javascript/routes.js` if `app/assets/javascripts` doesn't exist 
* Added `default` export key for better es6 experience.

I would be grateful if someone can try to use the gem from master and report of these features are working correctly.

**Comment by marvinthepa** [comment]
I have not had any issues using

```
import Routes from '../app/javascript/js-routes'
```

using 1.4.9, so I do not know why 7c654aa0c305 is necessary. But then again, I am far from being an expert on that topic.

**Comment by itsNikolay** [comment]
Just leave my notes how I migrated from Sprockets to Webpacker, perhaps somebody helps

1. remove/rename `assets` directory

```sh
$ mv app/assets app/deprecated_assets
```

2. Generate js-routes file with (every time when you update `routes.rb` file)

```ruby
$ rails js:routes
```

3. Make sure it created `app/javascripts/routes.js`

4. Add trinspiler to import `routes.js` file

```sh
$ yarn add @babel/plugin-transform-modules-umd
```
5. ./babel.config.js

```js
    plugins: [
      require('@babel/plugin-transform-modules-umd'), // to import `JsRoutes.generate!` file
    ]
  }
}
```

6. ./app/javascript/packs/application.js

```js
import Routes from 'routes'
// backward compatibility
window.Routes = document.Routes = Routes
```
7. Enjoy! 👍

**Comment by bogdan** [comment]
@itsNikolay can you explain why you would need `@babel/plugin-transform-modules-umd` to make it work? Can you try `1.4.11` and see if it works without it?

**Comment by sec0ndhand** [comment]
@bogdan I know I'm not @itsNikolay, but I was having the same problem.  I upgraded my package from 1.4.9 to 1.4.13 and it broke my app.  I was using the asset pipeline, but decided to make the jump and start using Webpacker for js-routes since we already have react in our project, and are using Webpacker already.

I followed the set up in the readme that explains using app/javascript/routes.js.erb and I was getting this error in the browser: 
```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
```
Once I added @babel/plugin-transform-modules-umd the error went away.  A UMD bundle, though making your shipped JS larger, allows it to be imported across browsers, nodejs, commonjs among others.  Anyway, maybe a consideration would be to ship jsroutes with an option to create a UMD bundle instead, which would eliminate the need for the babel plugin.  Thanks for all your hard work, it really helps those of us that know rails, but need to code in JS!

**Comment by bogdan** [comment]
@sec0ndhand I did what I could in v1.4.14. It is hard to make it work for all environments- js is such a mess. Can you try that and see if it works without `@babel/plugin-transform-modules-umd`?

**Comment by sec0ndhand** [comment]
Sorry it took so long @bogdan.  I have tried this, and this did not work once I removed `@babel/plugin-transform-modules-umd`.

**Comment by bogdan** [comment]
I've released v2.0 with complete support of ESM modules and webpacker. Webpacker setup is now in the readme. Please upgrade and open another issue if there are still problems.

**Comment by bogdan** [comment]
@le0pard it would be helpful if you could try upgrade guide https://github.com/railsware/js-routes/blob/master/VERSION_2_UPGRADE.md for any of your projects.

**Comment by le0pard** [comment]
@bogdan thanks. Will try later and will provide feedback (in PR or just as comment)

**Comment by le0pard** [comment]
@bogdan I did test on small project - all works. Currently I did not found project, which using js-routes in our company - all migrated to hardcoded values in JS :)
